 CREATE TABLE SGAS."DSA_ADVISOR_DEVICE_METADATA"
 (
	ID							NUMBER(5),
	USER_ID						VARCHAR2(100 BYTE) NOT NULL,
	EMAIL_ID					VARCHAR2(100 BYTE) NOT NULL,
	DEVICE_DETAILS				VARCHAR2(200 BYTE),
	BROWSER	 		            VARCHAR2(200 BYTE),
	PLATFORM					VARCHAR2(200 BYTE),
	IP_ADDRESS					VARCHAR2(200 BYTE),
	LAST_LOGGED_IN				DATE,
	DEVICE_VERIFICATION_DATE	DATE,
	DEVICE_VERIFICATION_STATUS	VARCHAR2(200 BYTE),
	DEVICE_VERIFICATION_TOKEN	VARCHAR2(200 BYTE),
	REMEMBER_DEVICE				VARCHAR2(1 BYTE)
);

ALTER TABLE SGAS."DSA_ADVISOR_DEVICE_METADATA" ADD PRIMARY KEY(ID);