ALTER TABLE DSA_APP_STUD_TRAVEL_EXP
    ADD VEHICLE_TYPE VARCHAR2(25) default '' NULL;
ALTER TABLE DSA_APP_STUD_TRAVEL_EXP
    ADD FUEL_COST NUMBER(7, 2) default 0 NULL;
ALTER TABLE DSA_APP_STUD_TRAVEL_EXP
    ADD MILES_PER_LITRE NUMBER(2) default 0 NULL;
ALTER TABLE DSA_APP_STUD_TRAVEL_EXP
    ADD KWH_COST NUMBER(2) default 0 NULL;
ALTER TABLE DSA_APP_STUD_TRAVEL_EXP
    ADD KWH_CAPACITY NUMBER(2) default 0 NULL;
ALTER TABLE DSA_APP_STUD_TRAVEL_EXP
    ADD RANGE_OF_CAR NUMBER(3) default 0 NULL;
