ALTER TABLE DSA_APP_STUD_TRAVEL_EXP ADD (KWH_COST_TEMP NUMBER(4,2));

UPDATE DSA_APP_STUD_TRAVEL_EXP SET KWH_COST_TEMP = KWH_COST;

UPDATE DSA_APP_STUD_TRAVEL_EXP SET KWH_COST = NULL;
 
ALTER TABLE DSA_APP_STUD_TRAVEL_EXP MODIFY KWH_COST NUMBER(4,2);

UPDATE DSA_APP_STUD_TRAVEL_EXP SET KWH_COST = KWH_COST_TEMP;

ALTER TABLE DSA_APP_STUD_TRAVEL_EXP DROP COLUMN KWH_COST_TEMP;