ALTER TABLE SGAS.DSA_APP_STUD_DISABILITIES modify( CREATED_BY varchar2(100), last_updated_by  varchar2(100));
ALTER TABLE SGAS.DSA_APP_STUD_ASSESSMENT_FEE   modify (CREATED_BY varchar2(100), LAST_UPDATED_BY varchar2(100));
ALTER TABLE SGAS.DSA_APP_STUD_CONSUMABLES   modify ( CREATED_BY varchar2(100),LAST_UPDATED_BY varchar2(100));
ALTER TABLE  SGAS.DSA_APP_STUD_LARGE_ITEMS    modify (CREATED_BY varchar2(100),LAST_UPDATED_BY varchar2(100));
ALTER TABLE  SGAS.DSA_APP_STUD_NMPH    modify (CREATED_BY varchar2(100),LAST_UPDATED_BY varchar2(100));
ALTER TABLE  SGAS.DSA_APP_STUD_TRAVEL_EXP    modify (CREATED_BY varchar2(100),LAST_UPDATED_BY varchar2(100));
ALTER TABLE  SGAS.DSA_APPLICATION_SECTION_STATUS    modify (CREATED_BY varchar2(100),LAST_UPDATED_BY varchar2(100));
ALTER TABLE  SGAS.DSA_APPLICATIONS_MADE    modify (CREATED_BY varchar2(100),LAST_UPDATED_BY varchar2(100));
ALTER TABLE  SGAS.DSA_APP_STUD_TRAVEL_PROVIDER    modify (CREATED_BY varchar2(100),LAST_UPDATED_BY varchar2(100));
    