CREATE TABLE SGAS."DSA_EMAIL_NOTIFICATION" (
ID                   	NUMBER(10)    	NOT NULL PRIMARY KEY,
STUD_REF_NO          	NUMBER(10)    	NOT NULL,
NOTIFICATION_TYPE       VARCHAR2(50)   	NOT NULL,
FAILURE_DATE			DATE            NULL,
FAILURE_REASON			VARCHAR2(500)   NULL,
SUCCESS_DATE 	 		DATE            NULL
);