CREATE TABLE SGAS."DSA_APP_STUD_ASSESSMENT_FEE" (
ID                   	NUMBER(10)    	NOT NULL PRIMARY KEY,
DSA_APPLICATION_NO   	NUMBER(10)    	NOT NULL,
STUD_REF_NO          	NUMBER(10)    	NOT NULL,
ASSESSMENT_CENTRE_NAME 	VARCHAR2(150)  	NOT NULL,
ASSESSOR_NAME			VARCHAR2(150)   NOT NULL,
TOTAL_HOURS 			NUMBER(4)   	NOT NULL,
CREATED_BY	         	VARCHAR2(10)  NOT NULL,
CREATED_DATE	     	DATE          NOT NULL,
LAST_UPDATED_BY	     	VARCHAR2(10)  NOT NULL,	
LAST_UPDATED_DATE	 	DATE          NOT NULL,
COST	                NUMBER(7,2)   NOT NULL
);

ALTER TABLE SGAS."DSA_APP_STUD_ASSESSMENT_FEE" ADD CONSTRAINT DSA_APP_STUD_ASSESS_FEE_FK FOREIGN KEY (DSA_APPLICATION_NO) REFERENCES SGAS."DSA_APPLICATIONS_MADE";