CREATE TABLE SGAS."DSA_APP_STUD_BANK_ACCOUNT" (
ID                   	NUMBER(10)    	NOT NULL PRIMARY KEY,
DSA_APPLICATION_NO   	NUMBER(10)    	NOT NULL,
STUD_REF_NO          	NUMBER(10)    	NOT NULL,
ACCOUNT_NAME			VARCHAR2(50)   	NOT NULL,
SORT_CODE 	 			VARCHAR2(8)   	NOT NULL,
ACCOUNT_NUMBER          VARCHAR2(8)   	NOT NULL,
PAYMENT_FOR             VARCHAR2(75)   	NOT NULL
);

ALTER TABLE SGAS."DSA_APP_STUD_BANK_ACCOUNT" ADD CONSTRAINT DSA_APP_STUD_BANK_ACCOUNT_FK FOREIGN KEY (DSA_APPLICATION_NO) REFERENCES SGAS."DSA_APPLICATIONS_MADE";