CREATE TABLE SGAS."DSA_CMS_TEXT"
(
  IDENTIFIER  VARCHAR2(50 BYTE),
  CONTENT     VARCHAR2(4000 BYTE)
);

ALTER TABLE SGAS."DSA_CMS_TEXT" ADD PRIMARY KEY(IDENTIFIER);

-- DSA_APPLICATIONS_MADE tables

CREATE TABLE  SGAS."DSA_APPLICATIONS_MADE"
(
  DSA_APPLICATION_NO      NUMBER(10)            NOT NULL,
  STUD_REF_NO             NUMBER(10)            NOT NULL,
  APPLICATION_STATUS      VARCHAR2(50)          NOT NULL,

  CREATED_BY              VARCHAR2(20)          NOT NULL,
  CREATED_DATE			  DATE 					NOT NULL,
  LAST_UPDATED_BY         VARCHAR2(20)          NOT NULL,
  LAST_UPDATED_DATE		  DATE 					NOT NULL
);

ALTER TABLE SGAS."DSA_APPLICATIONS_MADE" ADD PRIMARY KEY(DSA_APPLICATION_NO);

-- DSA_APPLICATION_SECTION_STATUS tables

CREATE TABLE  SGAS."DSA_APPLICATION_SECTION_STATUS"
(
	ID      				NUMBER(10)            NOT NULL,
	DSA_APPLICATION_NO      NUMBER(10)            NOT NULL,
	STUD_REF_NO             NUMBER(10)            NOT NULL,
	SECTION_PART            VARCHAR2(5)           NOT NULL,
	SECTION_CODE            VARCHAR2(25)          NOT NULL,
	SECTION_STATUS          VARCHAR2(25)          NOT NULL,

	CREATED_BY              VARCHAR2(20)          NOT NULL,
    CREATED_DATE			DATE         		  NOT NULL,
    LAST_UPDATED_BY         VARCHAR2(20)          NOT NULL,
    LAST_UPDATED_DATE		DATE 				  NOT NULL

);

ALTER TABLE SGAS."DSA_APPLICATION_SECTION_STATUS" ADD PRIMARY KEY(ID);


ALTER TABLE SGAS."DSA_APPLICATION_SECTION_STATUS" ADD CONSTRAINT DSA_APP_NO_FK FOREIGN KEY (DSA_APPLICATION_NO) REFERENCES SGAS."DSA_APPLICATIONS_MADE";