 CREATE TABLE SGAS."DSA_STUDENT_AUTH_DETAILS"
 (
	SUID    	 				VARCHAR2(25 BYTE)     NOT NULL PRIMARY KEY,
	STUD_REF_NO         		NUMBER(10),
	DSA_APPLICATION_NO	 		NUMBER(10),
	ACTIVATION_TOKEN 	        VARCHAR2 (100 BYTE),
	ACTIVATION_REQUEST_DATE  	DATE,
	IS_LOGGED_IN				VARCHAR2 (1 BYTE),
	LAST_LOGGED_IN_DATE			DATE
);