CREATE TABLE SGAS."DSA_QUOTE_PDF"
(
QUOTE_ID                   	NUMBER(10)    	NOT NULL PRIMARY KEY,
QUOTE                       BLOB,
QUOTE_FILE_NAME             VARCHAR2(200)   	NOT NULL,
OBJECT_ID      	            VARCHAR2(100),
DSA_APPLICATION_NO   	    NUMBER(10)    	NOT NULL,
STUD_REF_NO         	    NUMBER(10)    	NOT NULL,
STUD_CRSE_YEAR_ID			NUMBER(10)   	NOT NULL,
SESSION_CODE 	 			NUMBER(4)   	NOT NULL,
ADVISOR_ID                  VARCHAR2(10)   	NOT NULL,
QUOTE_REFERENCE             VARCHAR2(100)   	NOT NULL,
QUOTE_COST                  VARCHAR2(10)   	NOT NULL,
SUPPLIER                    VARCHAR2(100)   	NOT NULL,
CREATED_DATE			    DATE,
LAST_UPDATED_DATE		    DATE
);