CREATE TABLE SGAS."DSA_APP_STUD_ACCOMMODATION" (
	ID                   	NUMBER(10)    NOT NULL PRIMARY KEY,
	DSA_APPLICATION_NO   	NUMBER(10)    NOT NULL,
	STUD_REF_NO          	NUMBER(10)    NOT NULL,
	ACCOMMODATION_TYPE 		VARCHAR2(20)  NOT NULL,
	STANDARD_COST		    NUMBER(7,2)   NULL,
	ENHANCED_COST		    NUMBER(7,2)   NULL,
	WEEKS             		NUMBER(2)     NULL,
	CREATED_BY	  		 	VARCHAR2(100)  NULL,	
	CREATED_DATE	     	DATE          NULL,
	LAST_UPDATED_BY	     	VARCHAR2(100)  NULL,	
	LAST_UPDATED_DATE	 	DATE          NULL
);

ALTER TABLE SGAS."DSA_APP_STUD_ACCOMMODATION" ADD CONSTRAINT DSA_APP_STUD_ACCOM_FK FOREIGN KEY (DSA_APPLICATION_NO) REFERENCES SGAS."DSA_APPLICATIONS_MADE";