CREATE TABLE SGAS."DSA_APP_ADDITIONAL_INFO"
(
DSA_APPLICATION_NO   		NUMBER(10)    NOT NULL,
INFO_TEXT					VARCHAR2(500) 	NULL,
CREATED_BY	         		VARCHAR2(100)  NOT NULL,
CREATED_DATE	     		DATE          NOT NULL,
LAST_UPDATED_BY	     		VARCHAR2(100)  NOT NULL,	
LAST_UPDATED_DATE	 		DATE          NOT NULL
);

ALTER TABLE SGAS."DSA_APP_ADDITIONAL_INFO" ADD CONSTRAINT NO_DUPLICATE_ADD_INFO UNIQUE (DSA_APPLICATION_NO);

ALTER TABLE SGAS."DSA_APP_ADDITIONAL_INFO" ADD CONSTRAINT DSA_ADDITIONAL_INFO_FK FOREIGN KEY (DSA_APPLICATION_NO) REFERENCES SGAS."DSA_APPLICATIONS_MADE";
