-- Adding new reference table for payment for
CREATE TABLE SGAS."DSA_LRG_EQP_PAYMENT_FOR"
(
STUD_REF_NO          		NUMBER(10)    NOT NULL,
DSA_APPLICATION_NO   		NUMBER(10)    NOT NULL,
SESSION_CODE            	NUMBER(10)    NOT NULL,
PAYMENT_FOR					VARCHAR2(20)  NOT NULL,
CREATED_DATE			    DATE NOT NULL,
LAST_UPDATED_DATE		    DATE NOT NULL
);

ALTER TABLE SGAS."DSA_LRG_EQP_PAYMENT_FOR" ADD CONSTRAINT NO_DUPLICATE_PAYMENT UNIQUE(STUD_REF_NO, DSA_APPLICATION_NO, SESSION_CODE, PAYMENT_FOR); 

-- Adding new reference table for university fetch
CREATE TABLE SGAS."DSA_LRG_EQP_INST_PYMT"
(
ID                    	    NUMBER(10)    	NOT NULL PRIMARY KEY,
INSTITUTE_NAME              VARCHAR2(200)   	NOT NULL,
CREATED_DATE			    DATE NOT NULL,
LAST_UPDATED_DATE		    DATE NOT NULL
);


INSERT  INTO SGAS."DSA_LRG_EQP_INST_PYMT" (ID, INSTITUTE_NAME, CREATED_DATE, LAST_UPDATED_DATE)            
VALUES  (1, 'HERIOT-WATT UNIVERSITY', SYSTIMESTAMP, SYSTIMESTAMP);

