ALTER TABLE DSA_APPLICATIONS_MADE  RENAME COLUMN APPLICATION_STATUS TO APP_SUMMARY_STATUS;
ALTER TABLE DSA_APPLICATIONS_MADE ADD (APP_STATUS VARCHAR2(50 BYTE), SESSION_CODE NUMBER (4));
UPDATE DSA_APPLICATIONS_MADE SET APP_STATUS = 'STARTED';
UPDATE DSA_APPLICATIONS_MADE SET SESSION_CODE = 2024;