CREATE TABLE SGAS."DSA_AWARD_ACCESS"
(
DSA_APPLICATION_NO   		NUMBER(10)    NOT NULL,
ADVISOR_CAN_ACCESS			VARCHAR2(1)   NOT NULL,
CREATED_DATE			    DATE NOT NULL,
LAST_UPDATED_DATE		    DATE NOT NULL
);

ALTER TABLE SGAS."DSA_AWARD_ACCESS" ADD CONSTRAINT NO_DUPLICATE_AWARD_ACCESS UNIQUE (DSA_APPLICATION_NO);

ALTER TABLE SGAS."DSA_AWARD_ACCESS" ADD CONSTRAINT DSA_AWARD_ACCESS_FK FOREIGN KEY (DSA_APPLICATION_NO) REFERENCES SGAS."DSA_APPLICATIONS_MADE";
