 CREATE TABLE SGAS."DSA_ADVISOR"
 (
	ADVISOR_ID						NUMBER(10),
	FIRST_NAME						VARCHAR2(50 BYTE),
	LAST_NAME						VARCHAR2(50 BYTE),
	EMAIL		    	            VARCHAR2(100 BYTE) NOT NULL,
	INSTITUTION				    	VARCHAR2(100 BYTE),
	TEAM_EMAIL            	    	VARCHAR2(100 BYTE),
	INST_CODE				    	VARCHAR2(10 BYTE),
	CREATED_DATE            		DATE,
	LAST_UPDATED_DATE				DATE,
	IS_ACTIVE						VARCHAR2(1 BYTE),
	USER_ID                         VARCHAR(10),
	ROLE_NAME                       VARCHAR(50)
);

ALTER TABLE SGAS."DSA_ADVISOR" ADD PRIMARY KEY(EMAIL);

 CREATE TABLE SGAS."DSA_ROLES"
 (
	ROLE_ID    	        	    	NUMBER(10)          NOT NULL,
	ROLE_NAME          				VARCHAR2(100 BYTE),
	DESCRIPTION	 	        		VARCHAR2(100 BYTE),
	CREATED_DATE            		DATE,
	LAST_UPDATED_DATE				DATE
);

ALTER TABLE SGAS."DSA_ROLES" ADD PRIMARY KEY(ROLE_ID);

CREATE SEQUENCE SGAS.DEVICE_ID_SEQ
  START WITH 101
  MAXVALUE 10000000000000
  MINVALUE 101
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE SEQUENCE SGAS.ADVISOR_ID_SEQ
  START WITH 101
  MAXVALUE 99999999999999
  MINVALUE 101
  NOCYCLE
  NOCACHE
  NOORDER;
