CREATE TABLE  SGAS."DSA_DISABILITY_TYPE"
(
  DISABILITY_TYPE_ID      		NUMBER(2)		NOT NULL, 
  DISABILITY_TYPE_CODE      	VARCHAR2(75)    NOT NULL,
  DISABILITY_TYPE_DESC      	VARCHAR2(200)    NOT NULL,
  DISABILITY_TYPE_HINT_TEXT     VARCHAR2(350)   NOT NULL,
  IS_ACTIVE 					VARCHAR2(3)     NOT NULL, 
  LAST_UPDATED_BY         		VARCHAR2(20)    NOT NULL,
  LAST_UPDATED_DATE		  		DATE 			NOT NULL
);

 
ALTER TABLE SGAS."DSA_DISABILITY_TYPE" ADD PRIMARY KEY(DISABILITY_TYPE_ID);
-- To Prevent duplicates for DISABILITY_TYPE_CODE
ALTER TABLE SGAS."DSA_DISABILITY_TYPE" ADD CONSTRAINT NO_DUPLICATE_DIS_CODE UNIQUE(DISABILITY_TYPE_CODE);
 
-- Inserting the disability types data
INSERT  INTO SGAS.DSA_DISABILITY_TYPE (DISABILITY_TYPE_ID, DISABILITY_TYPE_CODE, DISABILITY_TYPE_DESC, DISABILITY_TYPE_HINT_TEXT, IS_ACTIVE, LAST_UPDATED_BY, LAST_UPDATED_DATE)            
VALUES  (1, 'LONG_LASTING_ILLNESS', 'A longstanding illness or health condition', 'An ongoing, often unseen condition such as diabetes, MS, arthritis, epilepsy, asthma, back pain or chronic heart disease.', 'YES', 'SGAS', SYSTIMESTAMP);

INSERT  INTO SGAS.DSA_DISABILITY_TYPE (DISABILITY_TYPE_ID, DISABILITY_TYPE_CODE, DISABILITY_TYPE_DESC, DISABILITY_TYPE_HINT_TEXT, IS_ACTIVE, LAST_UPDATED_BY, LAST_UPDATED_DATE)            
VALUES  (2, 'SOCIAL_COMMUNICATION_IMPAIRMENT', 'A social or communication impairment', 'Including and not limited to Asperger''s Syndrome, autistic spectrum disorder, ADHD, a speech disorder, or social, emotional or behavioural difficulty.','YES', 'SGAS', SYSTIMESTAMP);


INSERT  INTO SGAS.DSA_DISABILITY_TYPE (DISABILITY_TYPE_ID, DISABILITY_TYPE_CODE, DISABILITY_TYPE_DESC, DISABILITY_TYPE_HINT_TEXT, IS_ACTIVE, LAST_UPDATED_BY, LAST_UPDATED_DATE)            
VALUES  (3, 'PHYSICAL_IMPAIRMENT', 'A physical impairment or mobility issues', 'A physical health issue that limits motor skills and mobility, such as difficulty using arms, or a wheelchair or crutches user.', 'YES', 'SGAS', SYSTIMESTAMP);

INSERT  INTO SGAS.DSA_DISABILITY_TYPE (DISABILITY_TYPE_ID, DISABILITY_TYPE_CODE, DISABILITY_TYPE_DESC, DISABILITY_TYPE_HINT_TEXT, IS_ACTIVE, LAST_UPDATED_BY, LAST_UPDATED_DATE)            
VALUES  (4, 'MENTAL_HEALTH', 'A mental health condition', 'Including and not limited to depression, bipolar disorder, PTSD, schizophrenia or anxiety.', 'YES', 'SGAS', SYSTIMESTAMP);


INSERT  INTO SGAS.DSA_DISABILITY_TYPE (DISABILITY_TYPE_ID, DISABILITY_TYPE_CODE, DISABILITY_TYPE_DESC, DISABILITY_TYPE_HINT_TEXT, IS_ACTIVE, LAST_UPDATED_BY, LAST_UPDATED_DATE)            
VALUES  (5, 'VISUAL_IMPAIRMENT', 'A visual impairment', 'Blind or serious visual impairment.', 'YES', 'SGAS', SYSTIMESTAMP);


INSERT  INTO SGAS.DSA_DISABILITY_TYPE (DISABILITY_TYPE_ID, DISABILITY_TYPE_CODE, DISABILITY_TYPE_DESC, DISABILITY_TYPE_HINT_TEXT, IS_ACTIVE, LAST_UPDATED_BY, LAST_UPDATED_DATE)            
VALUES  (6, 'HEARING_IMPAIRMENT', 'A hearing impairment', 'Deaf or partial hearing.', 'YES', 'SGAS', SYSTIMESTAMP);


INSERT  INTO SGAS.DSA_DISABILITY_TYPE (DISABILITY_TYPE_ID, DISABILITY_TYPE_CODE, DISABILITY_TYPE_DESC, DISABILITY_TYPE_HINT_TEXT, IS_ACTIVE, LAST_UPDATED_BY, LAST_UPDATED_DATE)            
VALUES  (7, 'LEARNING_DIFFICULTY', 'A learning difficulty', 'A specific learning difficulty such as dyslexia, dyspraxia or ADHD.', 'YES', 'SGAS', SYSTIMESTAMP);

INSERT  INTO SGAS.DSA_DISABILITY_TYPE (DISABILITY_TYPE_ID, DISABILITY_TYPE_CODE, DISABILITY_TYPE_DESC, DISABILITY_TYPE_HINT_TEXT, IS_ACTIVE, LAST_UPDATED_BY, LAST_UPDATED_DATE)            
VALUES  (8, 'DISABILITY_NOT_LISTED', 'A disability not listed', 'Please describe the disability or specific learning difficulty:', 'YES', 'SGAS', SYSTIMESTAMP);

-- Student applciation disabilities 
CREATE TABLE  SGAS."DSA_APP_STUD_DISABILITIES"
(
	ID      					NUMBER(10)            NOT NULL, 
	DSA_APPLICATION_NO     	 	NUMBER(10)            NOT NULL,
	STUD_REF_NO             	NUMBER(10)            NOT NULL,
	DISABILITY_TYPE_CODE      	VARCHAR2(50)          NOT NULL,
	DISABILITY_NOTLISTED_TEXT   VARCHAR2(300),
	CREATED_BY                  VARCHAR2(20)          NOT NULL,
    CREATED_DATE			    DATE         		  NOT NULL,
    LAST_UPDATED_BY             VARCHAR2(20)          NOT NULL,
    LAST_UPDATED_DATE		    DATE 				  NOT NULL
	
);

ALTER TABLE SGAS."DSA_APP_STUD_DISABILITIES" ADD PRIMARY KEY(ID);

-- To Prevent duplicates for DSA_APPLICATION_NO and DISABILITY_TYPE_CODE
ALTER TABLE SGAS."DSA_APP_STUD_DISABILITIES" ADD CONSTRAINT NO_DUPLICATE_APP_NO_DIS_CODE UNIQUE(DSA_APPLICATION_NO, DISABILITY_TYPE_CODE);

ALTER TABLE SGAS."DSA_APP_STUD_DISABILITIES" ADD CONSTRAINT DSA_APP_STUD_DISABILITIES_FK FOREIGN KEY (DSA_APPLICATION_NO) REFERENCES SGAS."DSA_APPLICATIONS_MADE";

-- Updating the disability type description
update    SGAS.DSA_DISABILITY_TYPE set DISABILITY_TYPE_DESC =  'Longstanding illness or health condition' where DISABILITY_TYPE_ID = 1;
update    SGAS.DSA_DISABILITY_TYPE set DISABILITY_TYPE_DESC =  'Social or communication impairment' where DISABILITY_TYPE_ID = 2;
update    SGAS.DSA_DISABILITY_TYPE set DISABILITY_TYPE_DESC =  'Physical impairment or mobility issues' where DISABILITY_TYPE_ID = 3;
update    SGAS.DSA_DISABILITY_TYPE set DISABILITY_TYPE_DESC =  'Mental health condition' where DISABILITY_TYPE_ID = 4;
update    SGAS.DSA_DISABILITY_TYPE set DISABILITY_TYPE_DESC =  'Visual impairment' where DISABILITY_TYPE_ID = 5;
update    SGAS.DSA_DISABILITY_TYPE set DISABILITY_TYPE_DESC =  'Hearing impairment' where DISABILITY_TYPE_ID = 6;
update    SGAS.DSA_DISABILITY_TYPE set DISABILITY_TYPE_DESC =  'Learning difficulty' where DISABILITY_TYPE_ID = 7;
update    SGAS.DSA_DISABILITY_TYPE set DISABILITY_TYPE_DESC =  'Disability not listed' where DISABILITY_TYPE_ID = 8;