CREATE TABLE  SGAS."DSA_DECLARATION_TYPE"
(
  DECLARATION_TYPE_ID      		NUMBER(2)		NOT NULL,
  DECLARATION_TYPE_CODE      	VARCHAR2(50)    NOT NULL,
  DECLARATION_TYPE_DESC      	VARCHAR2(250)    NOT NULL,
  DECLARATION_FOR               VARCHAR2(10)   NOT NULL,
  IS_ACTIVE 					VARCHAR2(3)     NOT NULL, 
  LAST_UPDATED_BY         		VARCHAR2(20)    NOT NULL,
  LAST_UPDATED_DATE		  		DATE 			NOT NULL
);

-- Adding primary key
ALTER TABLE SGAS."DSA_DECLARATION_TYPE" ADD PRIMARY KEY(DECLARATION_TYPE_ID);
-- To Prevent duplicates for DECLARATION_TYPE_CODE
ALTER TABLE SGAS."DSA_DECLARATION_TYPE" ADD CONSTRAINT NO_DUPLICATE_DECLARATION_CODE UNIQUE(DECLARATION_TYPE_CODE);
 
-- Inserting the 'ADVISOR' DECLARATION types data
INSERT  INTO SGAS.DSA_DECLARATION_TYPE (DECLARATION_TYPE_ID, DECLARATION_TYPE_CODE, DECLARATION_TYPE_DESC, DECLARATION_FOR, IS_ACTIVE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES  (1, 'DETAILS_IN_THE_APP_ARE_CORRECT', 'Any support that is set out in the DSA claim is essential for this student to complete their course and to my knowledge, the details on this application are correct.', 'ADVISOR', 'YES', 'SGAS', SYSTIMESTAMP);

INSERT  INTO SGAS.DSA_DECLARATION_TYPE (DECLARATION_TYPE_ID, DECLARATION_TYPE_CODE, DECLARATION_TYPE_DESC, DECLARATION_FOR, IS_ACTIVE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES  (2, 'DISABILITIES_ARE_CORRECT', 'I have seen and verified medical evidence of a student’s disability or learning difficulty.', 'ADVISOR', 'YES', 'SGAS', SYSTIMESTAMP);

INSERT  INTO SGAS.DSA_DECLARATION_TYPE (DECLARATION_TYPE_ID, DECLARATION_TYPE_CODE, DECLARATION_TYPE_DESC, DECLARATION_FOR, IS_ACTIVE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES  (3, 'STUD_MEETS_REQUIREMENTS', 'I confirm student has undertaken a DSA needs assessment.', 'ADVISOR', 'YES', 'SGAS', SYSTIMESTAMP);
