 CREATE TABLE SGAS."DSA_ADVISOR_AUTH_DETAILS"
 (
	ADVISOR_ID						NUMBER(10),
	EMAIL							VARCHAR2(100 BYTE),
	ACCOUNT_ACTIVATION_STATUS		VARCHAR2(100 BYTE),
	ACCOUNT_ACTIVATION_TOKEN		VARCHAR2(100 BYTE),
	ACTIVATION_REQUEST_DATE			DATE,
	EMAIL_VERIFICATION_STATUS		VARCHAR2(100),
	EMAIL_VERIFICATION_TOKEN		VARCHAR2(100),
	EMAIL_VERIFICATION_DATE			DATE,
	TEMPORARY_LOCK_DATE_TIME		DATE,
	IS_TEMPORARY_LOCKED				VARCHAR2(1 BYTE),
	IS_PERMANENT_LOCKED				VARCHAR2(1 BYTE),	
	IS_LOGGED_IN					VARCHAR2(1 BYTE),	
	LAST_LOGGED_IN_DATE				DATE,
	PASSWORD_RESET_TOKEN			VARCHAR2(100 BYTE),
	PASSWORD_RESET_REQ_DATE_TIME	DATE,
	PROFILE_SAVED_DATE				DATE,
	REGISTERED_DATE					DATE,
	PERMANENT_LOCK_DATE				DATE,
	PREVIOUS_LOGIN_DATE				DATE,
	USER_ID                         VARCHAR(10),
    ROLE_NAME                       VARCHAR(50)
);

ALTER TABLE SGAS."DSA_ADVISOR_AUTH_DETAILS" ADD PRIMARY KEY(ADVISOR_ID);

ALTER TABLE SGAS."DSA_ADVISOR_AUTH_DETAILS" ADD CONSTRAINT DSA_ADV_EMAIL_FK FOREIGN KEY (EMAIL) 
REFERENCES SGAS."DSA_ADVISOR";

 CREATE TABLE SGAS."DSA_ADVISOR_LOGIN_DETAILS"
 (
	USER_ID							VARCHAR2(100 BYTE),
	USER_NAME						VARCHAR2(100 BYTE) NOT NULL,
	PASSWORD						VARCHAR2(200 BYTE),
	PREVIOUS_PASSWORD1 	            VARCHAR2(200 BYTE),
	PREVIOUS_PASSWORD2		    	VARCHAR2(200 BYTE),
	SALT					    	VARCHAR2(200 BYTE),
	SECRET_KEY				    	VARCHAR2(200 BYTE),
	ROLE					    	VARCHAR2(100 BYTE),
	LAST_LOGIN_TOKEN				VARCHAR2(200 BYTE),
	FAILED_PASSWORD_COUNT           NUMBER(2),
	CREATED_DATE            		DATE,
	LAST_UPDATED_DATE				DATE,
	IS_ACTIVE						VARCHAR2(1 BYTE)
);

ALTER TABLE SGAS."DSA_ADVISOR_LOGIN_DETAILS" ADD PRIMARY KEY(USER_NAME);