CREATE TABLE SGAS."DSA_APP_STUD_CONSUMABLES" (
ID                   	NUMBER(10)    NOT NULL PRIMARY KEY,
DSA_APPLICATION_NO   	NUMBER(10)    NOT NULL,
STUD_REF_NO          	NUMBER(10)    NOT NULL,
ITEM_CODE 				VARCHAR2(20)  NOT NULL,
OTHER_ITEM_DESC      	VARCHAR2(75)  NULL    ,
COST		           	NUMBER(7,2)   NOT NULL,
CREATED_BY	         	VARCHAR2(10)  NOT NULL,	
CREATED_DATE	     	DATE          NOT NULL,
LAST_UPDATED_BY	     	VARCHAR2(10)  NOT NULL,	
LAST_UPDATED_DATE	 	DATE          NOT NULL
);

ALTER TABLE SGAS."DSA_APP_STUD_CONSUMABLES" ADD CONSTRAINT DSA_APP_STUD_CONSUMABLES_FK FOREIGN KEY (DSA_APPLICATION_NO) REFERENCES SGAS."DSA_APPLICATIONS_MADE";
ALTER TABLE SGAS."DSA_APP_STUD_CONSUMABLES" ADD CONSTRAINT NO_DUPLICATE_APP_NO_ITEM UNIQUE(DSA_APPLICATION_NO, ITEM_CODE);

CREATE TABLE SGAS."DSA_APP_LRG_ITM_QUOTE" (
QUOTE_NO             	NUMBER(10)    NOT NULL PRIMARY KEY,
DSA_APPLICATION_NO   	NUMBER(10)    NOT NULL,
STUD_REF_NO          	NUMBER(10)    NOT NULL,
TOTAL_COST           	NUMBER(7,2)   NOT NULL,
SUPPLIER_NAME        	VARCHAR2(100),
QUOTE_REF            	VARCHAR2(20),
CREATED_BY	         	VARCHAR2(10)  NOT NULL,	
CREATED_DATE	    	DATE          NOT NULL,
LAST_UPDATED_BY	     	VARCHAR2(10)  NOT NULL,	
LAST_UPDATED_DATE	 	DATE          NOT NULL
);

ALTER TABLE SGAS."DSA_APP_LRG_ITM_QUOTE" ADD CONSTRAINT NO_DUPLICATE_APP_NO_QUOTE_REF UNIQUE(DSA_APPLICATION_NO, QUOTE_REF);

ALTER TABLE SGAS."DSA_APP_LRG_ITM_QUOTE" ADD CONSTRAINT DSA_APP_NO_LRG_ITM_QUOTE_FK FOREIGN KEY (DSA_APPLICATION_NO) REFERENCES SGAS."DSA_APPLICATIONS_MADE";

CREATE TABLE SGAS."DSA_APP_LRG_ITEM" (
ID                   	NUMBER(10)    NOT NULL PRIMARY KEY,
DSA_APPLICATION_NO   	NUMBER(10)    NOT NULL,
STUD_REF_NO          	NUMBER(10)    NOT NULL,
QUOTE_NO             	NUMBER(10)    NULL    ,
ITEM_TYPE_CODE       	VARCHAR2(20)  NOT NULL,
ITEM_NAME			 	VARCHAR2(75)  NOT NULL,
ITEM_COST            	NUMBER(7,2)   NOT NULL,
CREATED_BY	         	VARCHAR2(10)  NOT NULL,	
CREATED_DATE	     	DATE          NOT NULL,
LAST_UPDATED_BY	     	VARCHAR2(10)  NOT NULL,	
LAST_UPDATED_DATE	 	DATE          NOT NULL
);

ALTER TABLE SGAS."DSA_APP_LRG_ITEM" ADD CONSTRAINT DSA_APP_LRG_ITEM_FK FOREIGN KEY (DSA_APPLICATION_NO) REFERENCES SGAS."DSA_APPLICATIONS_MADE";

ALTER TABLE SGAS."DSA_APP_LRG_ITEM" ADD CONSTRAINT DSA_APP_LRG_ITEM_QUOTE_NO_FK FOREIGN KEY (QUOTE_NO) REFERENCES SGAS."DSA_APP_LRG_ITM_QUOTE";


CREATE TABLE SGAS."DSA_APP_STUD_NMPH" (
ID                   	NUMBER(10)    	NOT NULL PRIMARY KEY,
DSA_APPLICATION_NO   	NUMBER(10)    	NOT NULL,
STUD_REF_NO          	NUMBER(10)    	NOT NULL,
TYPE_OF_SUPPORT 		VARCHAR2(150)  	NOT NULL,
RECOMMENDED_PROVIDER	VARCHAR2(150)  NOT NULL,
HOURLY_RATE           	NUMBER(7,2)   	NOT NULL,
HOURS_PER_WEEK 			NUMBER(3)   	NOT NULL,
WEEKS             		NUMBER(2)   	NOT NULL,
COST		           	NUMBER(7,2)   	NOT NULL,
CREATED_BY	         	VARCHAR2(10)  NOT NULL,
CREATED_DATE	     	DATE          NOT NULL,
LAST_UPDATED_BY	     	VARCHAR2(10)  NOT NULL,
LAST_UPDATED_DATE	 	DATE          NOT NULL
);

ALTER TABLE SGAS."DSA_APP_STUD_NMPH" ADD CONSTRAINT DSA_APP_STUD_NMPH_FK FOREIGN KEY (DSA_APPLICATION_NO) REFERENCES SGAS."DSA_APPLICATIONS_MADE";