CREATE TABLE SGAS."DSA_APP_STUD_TRAVEL_EXP" (
TRAVEL_EXP_NO           NUMBER(10)    NOT NULL PRIMARY KEY,
DSA_APPLICATION_NO   	NUMBER(10)    NOT NULL,
STUD_REF_NO          	NUMBER(10)    NOT NULL,
TRAVEL_EXP_TYPE			VARCHAR2(12)  NOT NULL,
START_LOCATION_POSTCODE VARCHAR2(8)   NOT  NULL,
END_LOCATION_POSTCODE   VARCHAR2(8)   NOT  NULL,
RETURN_JOURNEYS        	NUMBER(3)     NOT NULL,
WEEKS_PER_ACADEMIC_YEAR NUMBER(2)     NOT NULL,
CREATED_BY	         	VARCHAR2(10)  NOT NULL,	
CREATED_DATE	     	DATE          NOT NULL,
LAST_UPDATED_BY	     	VARCHAR2(10)  NOT NULL,	
LAST_UPDATED_DATE	 	DATE          NOT NULL
);

ALTER TABLE SGAS."DSA_APP_STUD_TRAVEL_EXP" ADD CONSTRAINT DSA_APP_STUD_TRAVEL_EXP_FK FOREIGN KEY (DSA_APPLICATION_NO) REFERENCES SGAS."DSA_APPLICATIONS_MADE";
ALTER TABLE SGAS."DSA_APP_STUD_TRAVEL_EXP" ADD CONSTRAINT NO_DUPLICATE_APP_NO_EXP_TYPE UNIQUE(DSA_APPLICATION_NO, TRAVEL_EXP_TYPE);


CREATE TABLE SGAS."DSA_APP_STUD_TRAVEL_PROVIDER" (
ID                   	NUMBER(10)    NOT NULL PRIMARY KEY,
TRAVEL_EXP_NO			NUMBER(10)    NOT NULL,
PROVIDER_NAME 			VARCHAR2(50)  NOT  NULL,
IS_APPROVED_CONTRACT	VARCHAR2(3)   NOT  NULL,
COST		           	NUMBER(7,2)   NOT NULL,
CREATED_BY	         	VARCHAR2(10)  NOT NULL,	
CREATED_DATE	     	DATE          NOT NULL,
LAST_UPDATED_BY	     	VARCHAR2(10)  NOT NULL,	
LAST_UPDATED_DATE	 	DATE          NOT NULL
);
ALTER TABLE SGAS."DSA_APP_STUD_TRAVEL_PROVIDER" ADD CONSTRAINT DSA_APP_STUD_TRAVEL_PROV_FK FOREIGN KEY (TRAVEL_EXP_NO) REFERENCES SGAS."DSA_APP_STUD_TRAVEL_EXP";