CREATE TABLE SGAS."DSA_APP_STUD_LARGE_ITEMS"
(
    ID                 NUMBER(10)   NOT NULL PRIMARY KEY,
    DSA_APPLICATION_NO NUMBER(10)   NOT NULL,
    STUD_REF_NO        NUMBER(10)   NOT NULL,
    PRODUCT_NAME       VARCHAR2(50) NOT NULL,
    DESCRIPTION        VARCHAR2(300),
    COST               NUMBER(7, 2) NOT NULL,
    CREATED_BY         VARCHAR2(10) NOT NULL,
    CREATED_DATE       DATE         NOT NULL,
    LAST_UPDATED_BY    VARCHAR2(10) NOT NULL,
    LAST_UPDATED_DATE  DATE         NOT NULL
);

ALTER TABLE SGAS."DSA_APP_STUD_LARGE_ITEMS"
    ADD CONSTRAINT DSA_APP_STUD_LARGE_ITEMS_FK FOREIGN KEY (DSA_APPLICATION_NO) REFERENCES SGAS."DSA_APPLICATIONS_MADE";